"""user modified

Revision ID: 0d2c6560b0ef
Revises: f31ce643eb33
Create Date: 2023-06-28 13:30:45.092709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d2c6560b0ef'
down_revision = 'f31ce643eb33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('firebase_uid', table_name='users')
    op.drop_column('users', 'firebase_uid')
    op.drop_column('users', 'facebook_token')
    op.drop_column('users', 'google_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_token', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('users', sa.Column('facebook_token', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('users', sa.Column('firebase_uid', mysql.VARCHAR(length=128), nullable=True))
    op.create_index('firebase_uid', 'users', ['firebase_uid'], unique=False)
    # ### end Alembic commands ###
