"""Modify User model

Revision ID: 5d7dc5d27201
Revises: c6d9086d2c5f
Create Date: 2023-06-22 13:26:16.992855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d7dc5d27201'
down_revision = 'c6d9086d2c5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_token', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('facebook_token', sa.String(length=256), nullable=True))
    op.drop_index('facebook_id', table_name='users')
    op.drop_index('google_id', table_name='users')
    op.drop_column('users', 'facebook_id')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('facebook_id', mysql.VARCHAR(length=128), nullable=True))
    op.create_index('google_id', 'users', ['google_id'], unique=False)
    op.create_index('facebook_id', 'users', ['facebook_id'], unique=False)
    op.drop_column('users', 'facebook_token')
    op.drop_column('users', 'google_token')
    # ### end Alembic commands ###
